AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/MixinUsage:
  Exclude:
    - 'Rakefile'
