AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'schema.rb'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Style/MixinUsage:
  Exclude:
    - 'Rakefile'
