AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'schema.rb'

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Style/MixinUsage:
  Exclude:
    - 'Rakefile'
